#!/usr/bin/env python3
"""Generate a typed-client TypeScript file from a read-api endpoint inventory."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

BODY_METHODS = {"POST", "PUT", "PATCH"}
METHOD_ORDER = {
    "GET_COLLECTION": 0,
    "POST": 1,
    "GET_ITEM": 2,
    "PUT": 3,
    "PATCH": 3,
    "DELETE": 4,
}


def pascal(value: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", value)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def camel(value: str) -> str:
    p = pascal(value)
    return p[:1].lower() + p[1:] if p else value


def singular(value: str) -> str:
    if value.endswith("ies") and len(value) > 3:
        return value[:-3] + "y"
    if value.endswith("s") and len(value) > 1:
        return value[:-1]
    return value


def path_segments(path: str) -> list[str]:
    return [seg for seg in path.split("/") if seg and not is_param(seg)]


def is_param(segment: str) -> bool:
    return (
        segment.startswith(":")
        or (segment.startswith("{") and segment.endswith("}"))
    )


def endpoint_params(endpoint: dict[str, Any]) -> list[str]:
    params = endpoint.get("params")
    if isinstance(params, list):
        return [str(p) for p in params]
    found = []
    for segment in endpoint.get("path", "").split("/"):
        if segment.startswith(":"):
            found.append(segment[1:])
        elif segment.startswith("{") and segment.endswith("}"):
            found.append(segment[1:-1])
    return found


def operation_name(endpoint: dict[str, Any]) -> str:
    op_id = endpoint.get("operationId")
    if isinstance(op_id, str) and op_id:
        return op_id

    method = str(endpoint.get("method", "")).upper()
    params = endpoint_params(endpoint)
    segments = path_segments(str(endpoint.get("path", "")))
    last = singular(segments[-1]) if segments else "resource"
    resource = pascal(" ".join(singular(seg) for seg in segments)) or pascal(last)

    if method == "GET" and not params:
        return "list" + pascal(segments[-1] if segments else "resources")
    if method == "POST":
        return "create" + pascal(last)
    if method == "GET":
        return "get" + resource
    if method in {"PUT", "PATCH"}:
        return "update" + resource
    if method == "DELETE":
        return "delete" + resource
    return camel(method.lower() + " " + resource)


def url_literal(path: str, params: list[str]) -> str:
    templated = path
    for param in params:
        templated = templated.replace(f"{{{param}}}", "${" + param + "}")
        templated = templated.replace(f":{param}", "${" + param + "}")
    if params:
        return f"`{templated}`"
    return "'" + path.replace("\\", "\\\\").replace("'", "\\'") + "'"


def sort_key(endpoint: dict[str, Any], group_order: dict[str, int]) -> tuple[int, int, str]:
    method = str(endpoint.get("method", "")).upper()
    params = endpoint_params(endpoint)
    path = str(endpoint.get("path", ""))
    static_segments = path_segments(path)
    group = "/" + "/".join(static_segments[:1]) if static_segments else path
    if method == "GET":
        bucket = "GET_ITEM" if params else "GET_COLLECTION"
    else:
        bucket = method
    return (group_order.get(group, 999), METHOD_ORDER.get(bucket, 9), path)


def load_inventory(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text())
    if isinstance(payload, list):
        return {"source": path.name, "endpoints": payload}
    if isinstance(payload, dict) and isinstance(payload.get("endpoints"), list):
        return payload
    raise ValueError("endpoint inventory must be a list or a mapping with endpoints")


def generate(inventory: dict[str, Any], wrapper: str) -> str:
    source = inventory.get("source") or "endpoint inventory"
    raw_endpoints = list(inventory["endpoints"])
    group_order: dict[str, int] = {}
    for endpoint in raw_endpoints:
        static_segments = path_segments(str(endpoint.get("path", "")))
        group = "/" + "/".join(static_segments[:1]) if static_segments else str(endpoint.get("path", ""))
        if group not in group_order:
            group_order[group] = len(group_order)
    endpoints = sorted(raw_endpoints, key=lambda endpoint: sort_key(endpoint, group_order))
    lines = [
        f"// Generated by knowject-read-api from {source} using wrapper {wrapper}.",
        "// Do not edit by hand; re-run knowject-read-api to refresh.",
        f"import {{ request }} from '{wrapper}';",
        "",
    ]

    for endpoint in endpoints:
        method = str(endpoint.get("method", "")).upper()
        path = str(endpoint.get("path", ""))
        params = endpoint_params(endpoint)
        args = [f"{param}: string" for param in params]
        if method in BODY_METHODS:
            args.append("body: unknown")
        data = ", data: body" if method in BODY_METHODS else ""
        lines.append(f"export const {operation_name(endpoint)} = ({', '.join(args)}) =>")
        lines.append(
            f"  request<unknown>({{ method: '{method}', url: {url_literal(path, params)}{data} }});"
        )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("inventory", help="Endpoint inventory JSON from read-api extractor")
    parser.add_argument("--wrapper", required=True, help="HTTP wrapper import path")
    args = parser.parse_args()

    try:
        inventory = load_inventory(Path(args.inventory))
        sys.stdout.write(generate(inventory, args.wrapper))
    except Exception as exc:
        print(f"generate-typed-client failed: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
