// Generated by knowject-read-api from express-input.routes.ts using wrapper @knowject/request.
// Do not edit by hand; re-run knowject-read-api to refresh.
import { request } from '@knowject/request';

export const listUsers = () =>
  request<unknown>({ method: 'GET', url: '/users' });

export const createUser = (body: unknown) =>
  request<unknown>({ method: 'POST', url: '/users', data: body });

export const getUser = (id: string) =>
  request<unknown>({ method: 'GET', url: `/users/${id}` });

export const updateUser = (id: string, body: unknown) =>
  request<unknown>({ method: 'PATCH', url: `/users/${id}`, data: body });

export const deleteUser = (id: string) =>
  request<unknown>({ method: 'DELETE', url: `/users/${id}` });

export const getOrderItem = (orderId: string, itemId: string) =>
  request<unknown>({ method: 'GET', url: `/orders/${orderId}/items/${itemId}` });
