#!/usr/bin/env python3
"""Rewrite a knowject-read-api typed-client file with concrete response types.

Replaces request<unknown>(...) with request<TypeName>(...) at each endpoint
in the operations_mapping, and prepends an `import type` line for the types
that ended up being used.

Refuses to rewrite files missing the read-api header marker — this is the
contract that protects user-authored client files from accidental edits.

Day-1 scope: response types only. Body parameter typing is out of scope.
"""

import json
import re
import sys
from pathlib import Path


HEADER_MARKER = "Generated by knowject-read-api"


def find_endpoint_line(lines, method: str, path: str) -> int:
    """Find the line index of the request<unknown> call for a given endpoint.

    Strategy: locate a line containing request<unknown>, then check the next two
    lines for both the method literal and the path (in OpenAPI {param} form or
    JavaScript template ${param} form).
    """
    template_path = re.sub(r"\{([A-Za-z_][A-Za-z0-9_]*)\}", r"${\1}", path)
    method_re = re.compile(r"method:\s*['\"]" + re.escape(method) + r"['\"]", re.IGNORECASE)

    for i, line in enumerate(lines):
        if "request<unknown>" not in line:
            continue
        block = "\n".join(lines[i:i + 3])
        if not method_re.search(block):
            continue
        if template_path in block or path in block:
            return i
    return -1


def rewrite(client_text: str, mapping: list, module: str):
    """Return (new_text, changes, errors). If errors, new_text is None."""
    if HEADER_MARKER not in client_text:
        return None, [], [
            f"refuse to rewrite: required header marker '{HEADER_MARKER}' not found "
            f"(this file does not look like read-api output; emit-only mode should be "
            f"used by the Skill body in this case)"
        ]

    lines = client_text.splitlines(keepends=False)
    changes = []
    used_types: set = set()

    for op in mapping:
        method = op["method"]
        path = op["path"]
        rt = op.get("response_type")
        if not rt:
            changes.append({"endpoint": f"{method} {path}", "status": "no_response_type"})
            continue

        line_idx = find_endpoint_line(lines, method, path)
        if line_idx < 0:
            changes.append({"endpoint": f"{method} {path}", "status": "not_found"})
            continue

        for j in range(line_idx, min(line_idx + 5, len(lines))):
            if "request<unknown>" in lines[j]:
                lines[j] = lines[j].replace("request<unknown>", f"request<{rt}>", 1)
                changes.append(
                    {"endpoint": f"{method} {path}", "status": "rewrote", "type": rt}
                )
                used_types.add(rt)
                break

    new_text = "\n".join(lines) + ("\n" if client_text.endswith("\n") else "")

    if used_types:
        import_line = (
            f"import type {{ {', '.join(sorted(used_types))} }} from './{module}.types';"
        )
        out_lines = new_text.splitlines(keepends=False)
        if import_line not in out_lines:
            insert_at = 0
            for i, line in enumerate(out_lines):
                stripped = line.strip()
                if not stripped or stripped.startswith("//"):
                    continue
                insert_at = i
                break
            out_lines.insert(insert_at, import_line)
            new_text = "\n".join(out_lines) + ("\n" if client_text.endswith("\n") else "")

    return new_text, changes, []


def main() -> int:
    if len(sys.argv) != 4:
        print(
            "usage: rewrite-typed-client.py <client.ts> <extraction.json> <module>",
            file=sys.stderr,
        )
        return 2

    client_path = Path(sys.argv[1])
    mapping_path = Path(sys.argv[2])
    module = sys.argv[3]

    if not client_path.is_file():
        print(f"not a file: {client_path}", file=sys.stderr)
        return 2
    if not mapping_path.is_file():
        print(f"not a file: {mapping_path}", file=sys.stderr)
        return 2

    payload = json.loads(mapping_path.read_text())
    mapping = (
        payload["operations_mapping"]
        if isinstance(payload, dict) and "operations_mapping" in payload
        else payload
    )

    new_text, changes, errors = rewrite(client_path.read_text(), mapping, module)

    if errors:
        for e in errors:
            print(e, file=sys.stderr)
        return 1

    sys.stdout.write(new_text)
    print(f"changes: {len(changes)} (module={module})", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
