// Generated by knowject-api-to-types from Invalid Property Fixture.
// Module: users.
// Do not edit by hand — re-run knowject-api-to-types to refresh.

export interface ListUsersResponse {
  "display-name": string;
  "user id"?: string;
  ok_name?: number;
}
