// Generated by knowject-api-to-types from Fixture Users API.
// Module: users.
// Do not edit by hand — re-run knowject-api-to-types to refresh.

export type Role = "admin" | "member" | "guest";

export interface User {
  id: string;
  email: string;
  displayName?: string;
  role?: Role;
}

export interface CreateUserRequest {
  email: string;
  displayName?: string;
  role?: Role;
}

export interface UserListResponse {
  items: Array<User>;
  total: number;
}
