// Generated by knowject-read-design from sample-card-design.png.
// UI library: antd@6 (per knowject/context.yaml#stack.frontend.ui).
// Edit at will — re-running knowject-read-design will not overwrite this file unless you confirm.
import type { FC } from 'react';
import { Card, Tag } from 'antd';

interface ProjectCardProps {
  name: string;
  lastActiveLabel: string;
  knowledgeCount: number;
  recentItems: string[];
}

export const ProjectCard: FC<ProjectCardProps> = ({
  name,
  lastActiveLabel,
  knowledgeCount,
  recentItems,
}) => (
  <Card className="rounded-xl!" bordered={false}>
    <div className="flex items-start justify-between">
      <div>
        <h3 className="font-semibold text-lg">{name}</h3>
        <p className="text-xs text-slate-500 mt-1">最近活跃 {lastActiveLabel}</p>
      </div>
      <Tag color="blue">{knowledgeCount} 条</Tag>
    </div>
    <ul className="mt-4 space-y-2 text-sm text-slate-600">
      {recentItems.map((item) => (
        <li key={item}>· {item}</li>
      ))}
    </ul>
  </Card>
);
